# Generated by Django 6.0.6 on 2026-07-09 12:11

from typing import ClassVar

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies: ClassVar[list[tuple[str, str]]] = [
        ("core", "0002_token"),
    ]

    operations: ClassVar[list[object]] = [
        migrations.AddField(
            model_name="token",
            name="revoked_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="revoked at"
            ),
        ),
    ]
