name: Docker Build
on:
  pull_request:
  push:
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  docker-build:
    name: Docker build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4.1.0
      - name: Build Docker image
        uses: docker/build-push-action@v7.2.0
        with:
          context: .
          file: .docker/Dockerfile
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: UV_DEPENDENCY_GROUP=prod
