# Generated by Django 6.0.6 on 2026-07-07 17:01

from typing import ClassVar

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies: ClassVar[list[tuple[str, str]]] = [
        ("notes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations: ClassVar[list[object]] = [
        migrations.AddIndex(
            model_name="note",
            index=models.Index(
                fields=["owner", "-created_at"], name="notes_note_owner_i_b6b830_idx"
            ),
        ),
    ]
