from config.settings import env

DEFAULT_DATABASE = env.db("DATABASE_URL")
DEFAULT_DATABASE["CONN_HEALTH_CHECKS"] = True
DEFAULT_DATABASE["CONN_MAX_AGE"] = env.int(
    "DATABASE_CONN_MAX_AGE", default=env.int("CONN_MAX_AGE", default=60)
)
DEFAULT_DATABASE_OPTIONS = DEFAULT_DATABASE.setdefault("OPTIONS", {})
DEFAULT_DATABASE_OPTIONS.setdefault(
    "connect_timeout", env.int("DATABASE_CONNECT_TIMEOUT", default=5)
)
DATABASE_LOCK_TIMEOUT = env.int("DATABASE_LOCK_TIMEOUT", default=5_000)
DATABASE_STATEMENT_TIMEOUT = env.int("DATABASE_STATEMENT_TIMEOUT", default=15_000)
DEFAULT_DATABASE_OPTIONS["options"] = (
    f"-c lock_timeout={DATABASE_LOCK_TIMEOUT} "
    f"-c statement_timeout={DATABASE_STATEMENT_TIMEOUT}"
)
DATABASES = {"default": DEFAULT_DATABASE}
